services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: efcore-join-benchmark-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: "Your_strong_password123"
    ports:
      - "14333:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data: